---

- name: Create RabbitMQ exchanges
  rabbitmq_exchange:
    login_host: "{{ rabbitmq_config_host|default(omit) }}"
    login_port: "{{ rabbitmq_config_port|default(omit) }}"
    login_user: "{{ rabbitmq_config_user }}"
    login_password: "{{ rabbitmq_config_password }}"
    name: "{{ item.name }}"
    exchange_type: "{{ item.exchange_type }}"
    durable: "{{ item.durable|default('True') }}"
  with_items: "{{ rabbitmq_config_exchanges }}"
  ignore_errors: "{{ rabbitmq_config_ignore_errors|default(omit) }}"

- name: Create RabbitMQ queues
  rabbitmq_queue:
    login_host: "{{ rabbitmq_config_host|default(omit) }}"
    login_port: "{{ rabbitmq_config_port|default(omit) }}"
    login_user: "{{ rabbitmq_config_user }}"
    login_password: "{{ rabbitmq_config_password }}"
    name: "{{ item }}"
    dead_letter_exchange: "{{ item.dead_letter_exchange|default(omit) }}"
    durable: "{{ item.dead_letter_exchange|default(omit) }}"
    message_ttl: "{{ item.message_ttl|default(omit) }}"
  with_items: "{{ rabbitmq_config_queus }}"
  ignore_errors: "{{ rabbitmq_config_ignore_errors|default(omit) }}"

- name: Bind RabbitMQ queues to exchanges
  rabbitmq_binding:
    login_host: "{{ rabbitmq_config_host|default(omit) }}"
    login_port: "{{ rabbitmq_config_port|default(omit) }}"
    login_user: "{{ rabbitmq_config_user }}"
    login_password: "{{ rabbitmq_config_password }}"
    name: "{{ item.name }}"
    destination: "{{ item.destination }}"
    destination_type: "{{ item.destination_type }}"
    routing_key: "{{ item.routing_key|default(omit) }}"
  with_items: "{{ rabbitmq_config_bindings }}"
  ignore_errors: "{{ rabbitmq_config_ignore_errors|default(omit) }}"
